### ISSUE TITLE
Unknown shorthand flag: 'e' in -e

### ISSUE THREAD

**Issue by teehamaral** [anigeo/docker-awscli#2]
Currently anigeo/awscli returns a flag `-e none` when is runned `ecr get-login` command. Using the latest docker version, this argument isn't accepted (returning `Unknown shorthand flag: 'e' in -e` when `docker login` command is runned).

**Comment by WesleyCharlesBlake** [comment]
this is an issue with AWS cli, not this docker image. The `get-login` response is like this:

```
docker login -u AWS -p <some-really-long-token> -e none https://<your-aws-account>.dkr.ecr.us-west-2.amazonaws.com
```
If you ommit the `-e none` flag, you will be able to login

eg:
```
docker login -u AWS -p TOKEN_REDACTED https://ACCOUNT_REDACTED.dkr.ecr.us-west-2.amazonaws.com
Login Succeeded
```

**Comment by teehamaral** [comment]
Yeah, it's working. I did can do that there some weeks ago, thanks.
